* C++ project

* Design decisions
** The class itself  
The class members consists of char pointer to the beginning of the
buffer (m_buf) that holds the actual contents of the string, and two
size_t:s that are used to keep track of the size of the buffer
(m_bufsize), and the logical size of the string (m_used).  The m_buf
may be null if the string has no characters. In hindsight it would've
probably been more consistent to never allow m_buf to be null.

** The testdriver
The testdriver consists of a bunch of functions that take no arguments
and return no value. A test is succesful if the functions returns
normally, and test fails if the function throws an exception. The
drivers main() -function calls each of the test-functions and records
how many of them failed and succeeded, and also records the names of
the functions that failed, and prints this info into std::cout.


* What was difficult
 - getting it to compile
 - obscure messages from g++
 - keeping track of memory correctly
 - constness in general and in iterators in particular
 - io-operations because of statefulness
 
